Pytoch is a Python-based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs
- A deep learning research platform that provides maximum flexibility and speed

## Getting Started

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that **Tensors can also be used on a GPU to accelerate computing**.

In [ ]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:Construct a 5x3 matrix, uninitialized:

In [ ]:
# Construct an uninitialized 5x3 matrix
x = torch.empty(5, 3)
x

tensor([[9.9205e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 3.4516e-36]])

Construct a randomly initialized matrix:

In [ ]:
x = torch.rand(5, 3)
x

tensor([[0.1569, 0.7175, 0.9539],
        [0.6025, 0.4191, 0.1218],
        [0.9066, 0.4257, 0.1139],
        [0.2763, 0.7282, 0.0514],
        [0.5117, 0.1786, 0.0974]])

Construct a matrix filled with zeros and of dtype long:

In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

Construct a tensor directly from data:

In [ ]:
x = torch.tensor([1.5,2,3])
x

tensor([1.5000, 2.0000, 3.0000])

Create a tensor based on an existing tensor. These methods will **reuse properties of the input tensor**, e.g. dtype, unless new values are provided by user

In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

y = torch.randn_like(x, dtype=torch.float)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6442,  0.5110,  1.4605],
        [ 0.8740,  0.1232,  1.2665],
        [-1.2548, -1.2872,  0.1469],
        [ 0.1214, -0.4311, -0.0212],
        [-0.2303, -0.3831,  0.1935]])


Get its size:


In [ ]:
x.size()

torch.Size([5, 3])

### Operations

We take addition operation as example.

In [ ]:
y = torch.rand(5, 3)
y

tensor([[0.6240, 0.9044, 0.6271],
        [0.3672, 0.5607, 0.1855],
        [0.4983, 0.2105, 0.6499],
        [0.9172, 0.9049, 0.3101],
        [0.7206, 0.2368, 0.9177]])

In [ ]:
x + y

tensor([[1.6240, 1.9044, 1.6271],
        [1.3672, 1.5607, 1.1855],
        [1.4983, 1.2105, 1.6499],
        [1.9172, 1.9049, 1.3101],
        [1.7206, 1.2368, 1.9177]], dtype=torch.float64)

Provide an output tensor as argument:

In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[1.6240, 1.9044, 1.6271],
        [1.3672, 1.5607, 1.1855],
        [1.4983, 1.2105, 1.6499],
        [1.9172, 1.9049, 1.3101],
        [1.7206, 1.2368, 1.9177]])

In-place addition:
(Any operation that mutates a tensor in-place is post-fixed with an `_`)

In [ ]:
y.add_(x)

tensor([[1.6240, 1.9044, 1.6271],
        [1.3672, 1.5607, 1.1855],
        [1.4983, 1.2105, 1.6499],
        [1.9172, 1.9049, 1.3101],
        [1.7206, 1.2368, 1.9177]])

Use Numpy-like indexing:

In [ ]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [ ]:
print(x[:, 1])
print(x[:, 1].size())

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
torch.Size([5])


Use `torch.view` to resize/reshape tensor:

In [ ]:
x = torch.ones(4, 4)
print(f"x={x}")
print(f"size of x: {x.size()}")

x=tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
size of x: torch.Size([4, 4])


In [ ]:
y = x.view(16)
print(f"y={y}")
print(f"size of y: {y.size()}")

y=tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
size of y: torch.Size([16])


In [ ]:
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(f"z={z}")
print(f"size of z: {z.size()}")

z=tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
size of z: torch.Size([2, 8])


For one element tensor, use `.item` to get the value as a python number:

In [ ]:
x = torch.rand(1)
x

tensor([0.5530])

In [ ]:
x.item()

0.552950382232666

## Numpy Bridge

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

### Torch Tensor -> Numpy Array

Use `numpy()`

In [ ]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [ ]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

If both pytorch tensor and numpy array are on CPU, change one of them will change the another.

In [ ]:
# Change tensor
a.add_(1) # in-place addition
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Numpy Array -> Torch Tensor

Use `from_numpy()`

In [ ]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Change the np array will change the torch tensor automatically:

In [ ]:
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Note: All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## CUDA Tensors

- Tensors can be moved onto any device using the `.to` method.

- Use ``torch.device`` objects to move tensors in and out of GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
x

tensor([0.5530])

In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device) # Create a tensor on GPU directly
    x = x.to(device) # Move a tensor to GPU use .to()
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))


tensor([1.5530], device='cuda:0')
tensor([1.5530], dtype=torch.float64)
